version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: brass-web
    ports:
      - "8181:80"   # host:container
    volumes:
      - index.html:/usr/share/nginx/html:ro   # serve your static files
    restart: always
