name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - "helm/"
      - "k8s/"
      - "README.md"


jobs:
  docker-build-push:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"   # ignore [skip-ci] commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}     # save your docker user name in the repo's secret and variable section 
          password: ${{ secrets.DOCKERHUB_TOKEN }}        # generate token from docker hub and save as a variable in the secret and variable section


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/brass-web:${{ github.run_id }}


  update-helm-tag:
    if: "!contains(github.event.head_commit.message, '[skip ci]')" 
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Docker tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/brass-web-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "macdehnis301@gmail.com"
          git config --global user.name "dennis.io"
          git add helm/brass-web-chart/values.yaml
          git commit -m "Git action updated image tag in Helm chart at $(date '+%Y-%m-%d %H:%M:%S') [skip ci]" || echo "No changes to commit"
          git push

# Added [skip ci] in the commit message
# Ignore commits that contain [skip ci]
# This prevents the Helm update commit from retriggering the pipeline
